### ISSUE TITLE
Feel free to grab our list! 

### ISSUE THREAD

**Issue by bram-atmire** [inveniosoftware/counter-robots#1]
https://github.com/atmire/COUNTER-Robots

**Comment by lnielsen** [comment]
Thanks....yes, we're actually already grabbing your list, but it is via the Making Data Count project (https://github.com/CDLUC3/Make-Data-Count/tree/master/user-agents/lists) which has the list split into robots and machines since we need it for both research data metrics usage and plain COUNTER usage stats.

**Comment by lnielsen** [comment]
Actually, @bram-atmire, could you clarify under which license your list is released? In the repo I don't find anything about it (perhaps I'm just blind :-))

**Comment by bram-atmire** [comment]
@lnielsen great question! Can't believe we overlooked that. Will touch base with the counter folks about that, but hope it's as free/open as possible !!!

**Comment by bram-atmire** [comment]
MIT license - the information is now in place.

**Comment by lnielsen** [comment]
Awesome, thanks a lot!
